server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ssxrs312/mmbuy-config-center
          username:
          password:
          # 对应的文件夹
          search-paths: gateway-config,user-service-config,trade-service-config,stock-service-config,common-config,key-generator-config,scheduler-config
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092 #这里是测试，所以连到了腾讯云服务器上，注意要开放端口才行
          zk-nodes: 127.0.0.1:2181
          auto-create-topics: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    ip-address: 127.0.0.1  #告诉注册中心这个服务的公网ip，github可以真正访问到
#    prefer-ip-address: true
management:
  security:
    enabled: false
